import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import ChatLeftSection from "../../components/chat/ChatLeftSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen bg-primary_color flex text-white">
          {/* chat feature left section */}
          <ChatLeftSection />

          {/* chat feature right section */}
          <section className="w-full">{children}</section>
        </div>
      </body>
    </html>
  );
}
